[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
optimizer = true
optimizer_runs = 200
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read-write", path = "./" }]
gas_reports = ["*"]
via_ir = true
evm_version = "cancun"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[profile.ci.fuzz]
runs = 10_000

# https://holesky.etherscan.io/address/0x139afdecf7fc799d59bd3b915252944f73e155d5#code
# https://holesky.etherscan.io/address/0x00189cae228389b61f68b4e3520393941daad6e1#code
# https://holesky.etherscan.io/address/0xcEe2a0fFf54bd779CF17DF7d56AaaA9BFA68BC5E#code
